---
title: "Human Activity Recognition Using Smartphones Dataset"
date: "26 January 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Project description
The purpose of the project is to collect, work with and clean data for later analysis. The dataset to be cleaned is represents data collected from the accelerometers from the Samsung Galaxy S smartphone. 

The `run_analysis.R` script is used to complete the project.


#### Collection of the raw data
The experiments were carried out on a group of 30 volunteers, with each performing six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone on the waist.

For each record it is provided:
   - Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
   - Triaxial Angular velocity from the gyroscope. 
   - A 561-feature vector with time and frequency domain variables. 
   - Its activity label. 
   - An identifier of the subject who carried out the experiment.

A full description of the data can be obtained from the [UCI Machine Learning Repository website.]("http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones")

### Creating the tidy datafile
#### Collecting data for processing
Data was downloaded from the [UCI Machine Learning Repository website]("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip") and unzipped to 'UCI HAR Dataset' folder.

Of the extracted files, the following files and datasets were relevant to this project:
   - 'README.txt' - description of the data
   - 'features_info.txt': Shows information about the variables used on the feature vector.
   - 'features.txt': List of all features.
   - 'activity_labels.txt': Links the class labels with their activity name.
   - 'train/X_train.txt': Training set.
   - 'train/y_train.txt': Training labels.
   - 'test/X_test.txt': Test set.
   - 'test/y_test.txt': Test labels.
   - 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 
   - 'test/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

#### run_analysis script
The script does the following:
1. Merges the training and the test sets to create one data set.
   - cbind the datasets in the 'train' folder
   - cbind the datasets in the 'test' folder
   - rbind 'train' and 'test' data to make one dataset
   - column names were assigned based on the subject, activity performed and associated features
   
2. Extracts only the measurements on the mean and standard deviation for each
measurement.
   - selected based on variables containing "mean" or "std"
   
3. Uses descriptive activity names to name the activities in the data set
   - activity labels changed according to activity names. This was completed in part one after the data sets were merged
   
4. Appropriately labels the data set with descriptive variable names.
   - column names with "Acc" were replaced with "Accelerometer"
   - column names with "Gyro" were replaced with "Gyroscope"
   - column names with "Mag" were replaced with "Magnitude"
   - column names beginning with "t" were replaced with "Time"
   - column names beginning with "f" were replaced with "Frequency"
   - column names with "-mean()" were replaced with "Mean"
   - column names with "-std()" were replaced with "StdDeviation"
   - column names with "-freq-" were replaced with "Frequency"

5. From the data set in step 4, creates a second, independent tidy data set with the
average of each variable for each activity and each subject.
   - data exported to "ave_data.txt"


#### Variables in the final dataset:

[1] "Subject"         
        - integer type, indentifier for subjects [1:30]
 [2] "Activity"
        - character type, identifier for activity undertaken
                - WALKING
                - WALKING_UPSTAIRS
                - WALKING_DOWNSTAIRS
                - SITTING
                - STANDING
                - LAYING
                
Below are all of numeric type:     
 [3] "TimeBodyAccelerometerMean()-X"                            
 [4] "TimeBodyAccelerometerMean()-Y"                            
 [5] "TimeBodyAccelerometerMean()-Z"                            
 [6] "TimeGravityAccelerometerMean()-X"                         
 [7] "TimeGravityAccelerometerMean()-Y"                         
 [8] "TimeGravityAccelerometerMean()-Z"                         
 [9] "TimeBodyAccelerometerJerkMean()-X"                        
[10] "TimeBodyAccelerometerJerkMean()-Y"                        
[11] "TimeBodyAccelerometerJerkMean()-Z"                        
[12] "TimeBodyGyroscopeMean()-X"                                
[13] "TimeBodyGyroscopeMean()-Y"                                
[14] "TimeBodyGyroscopeMean()-Z"                                
[15] "TimeBodyGyroscopeJerkMean()-X"                            
[16] "TimeBodyGyroscopeJerkMean()-Y"                            
[17] "TimeBodyGyroscopeJerkMean()-Z"  
[18] "TimeBodyAccelerometerMagnitudeMean()"                     
[19] "TimeGravityAccelerometerMagnitudeMean()"                  
[20] "TimeBodyAccelerometerJerkMagnitudeMean()"                 
[21] "TimeBodyGyroscopeMagnitudeMean()"                         
[22] "TimeBodyGyroscopeJerkMagnitudeMean()"      
[23] "FrequencyBodyAccelerometerMean()-X"                       
[24] "FrequencyBodyAccelerometerMean()-Y"                       
[25] "FrequencyBodyAccelerometerMean()-Z"                       
[26] "FrequencyBodyAccelerometerMeanFreq()-X"                   
[27] "FrequencyBodyAccelerometerMeanFreq()-Y"                   
[28] "FrequencyBodyAccelerometerMeanFreq()-Z"         
[29] "FrequencyBodyAccelerometerJerkMean()-X"                   
[30] "FrequencyBodyAccelerometerJerkMean()-Y"                   
[31] "FrequencyBodyAccelerometerJerkMean()-Z"                   
[32] "FrequencyBodyAccelerometerJerkMeanFreq()-X"               
[33] "FrequencyBodyAccelerometerJerkMeanFreq()-Y"               
[34] "FrequencyBodyAccelerometerJerkMeanFreq()-Z"     
[35] "FrequencyBodyGyroscopeMean()-X"                           
[36] "FrequencyBodyGyroscopeMean()-Y"                           
[37] "FrequencyBodyGyroscopeMean()-Z"                           
[38] "FrequencyBodyGyroscopeMeanFreq()-X"                       
[39] "FrequencyBodyGyroscopeMeanFreq()-Y"                       
[40] "FrequencyBodyGyroscopeMeanFreq()-Z"   
[41] "FrequencyBodyAccelerometerMagnitudeMean()"                
[42] "FrequencyBodyAccelerometerMagnitudeMeanFreq()"            
[43] "FrequencyBodyBodyAccelerometerJerkMagnitudeMean()"        
[44] "FrequencyBodyBodyAccelerometerJerkMagnitudeMeanFreq()"   
[45] "FrequencyBodyBodyGyroscopeMagnitudeMean()"                
[46] "FrequencyBodyBodyGyroscopeMagnitudeMeanFreq()"            
[47] "FrequencyBodyBodyGyroscopeJerkMagnitudeMean()"            
[48] "FrequencyBodyBodyGyroscopeJerkMagnitudeMeanFreq()"  
[49] "angle(tBodyAccelerometerMean,gravity)"                    
[50] "angle(tBodyAccelerometerJerkMean),gravityMean)"           
[51] "angle(tBodyGyroscopeMean,gravityMean)"                    
[52] "angle(tBodyGyroscopeJerkMean,gravityMean)"                
[53] "angle(X,gravityMean)"                                     
[54] "angle(Y,gravityMean)"                                     
[55] "angle(Z,gravityMean)"           
[56] "TimeBodyAccelerometerStdDeviation()-X"                    
[57] "TimeBodyAccelerometerStdDeviation()-Y"                    
[58] "TimeBodyAccelerometerStdDeviation()-Z"                    
[59] "TimeGravityAccelerometerStdDeviation()-X"                 
[60] "TimeGravityAccelerometerStdDeviation()-Y"                 
[61] "TimeGravityAccelerometerStdDeviation()-Z"                 
[62] "TimeBodyAccelerometerJerkStdDeviation()-X"                
[63] "TimeBodyAccelerometerJerkStdDeviation()-Y"                
[64] "TimeBodyAccelerometerJerkStdDeviation()-Z"                
[65] "TimeBodyGyroscopeStdDeviation()-X"                        
[66] "TimeBodyGyroscopeStdDeviation()-Y"                        
[67] "TimeBodyGyroscopeStdDeviation()-Z"                        
[68] "TimeBodyGyroscopeJerkStdDeviation()-X"      
[69] "TimeBodyGyroscopeJerkStdDeviation()-Y"                    
[70] "TimeBodyGyroscopeJerkStdDeviation()-Z"                    
[71] "TimeBodyAccelerometerMagnitudeStdDeviation()"             
[72] "TimeGravityAccelerometerMagnitudeStdDeviation()"          
[73] "TimeBodyAccelerometerJerkMagnitudeStdDeviation()"         
[74] "TimeBodyGyroscopeMagnitudeStdDeviation()"                 
[75] "TimeBodyGyroscopeJerkMagnitudeStdDeviation()"             
[76] "FrequencyBodyAccelerometerStdDeviation()-X"               
[77] "FrequencyBodyAccelerometerStdDeviation()-Y"               
[78] "FrequencyBodyAccelerometerStdDeviation()-Z"               
[79] "FrequencyBodyAccelerometerJerkStdDeviation()-X"           
[80] "FrequencyBodyAccelerometerJerkStdDeviation()-Y"           
[81] "FrequencyBodyAccelerometerJerkStdDeviation()-Z"           
[82] "FrequencyBodyGyroscopeStdDeviation()-X"                   
[83] "FrequencyBodyGyroscopeStdDeviation()-Y"                   
[84] "FrequencyBodyGyroscopeStdDeviation()-Z"                   
[85] "FrequencyBodyAccelerometerMagnitudeStdDeviation()"        
[86] "FrequencyBodyBodyAccelerometerJerkMagnitudeStdDeviation()"
[87] "FrequencyBodyBodyGyroscopeMagnitudeStdDeviation()"        
[88] "FrequencyBodyBodyGyroscopeJerkMagnitudeStdDeviation()"




