---
title: "Getting and Cleaning Data Course Project"
date: "26 January 2022"
output:
  html_document: default
  pdf_document: default
---

### Getting and Cleaning Data Course Project
The goal is to prepare tidy data that can be used for later analysis. The data for the project represents data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available from <http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones>

Data can be downloaded from <https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip>

#### Repository info

This repository contains:

a. run_analysis.R script
b. tidy_ave.txt file which is the output of the second tiny data set above
c. README.Rmd which explains how the script works 
d. CodeBook.Rmd which describes the variables, data and any transformations or work performed to clean up the data
   
#### Script function
The run_analysis.R script does the following:

1. Reads the x, y and subject files from the 'train' and 'test' folders, while setting the column names for each variable
2. Uses column bind to merge the training data into one data set, then the test data into one data set
3. Then merges the train and test data sets together with a row bind to make one data set
4. Reads the activity labels and features, then uses descriptive activity names to name the activities in the data set 
5. Extracts only the measurements on the mean and standard deviation for each measurement 
6. Renames the data set with descriptive variable names via 'gsub'
7. From the data set in step 5, creates a second, independent tidy data set with the average of each variable for each activity and each subject (tidy_ave).

